#!/usr/bin/env bash

################################################################################
set -eu
set -o pipefail

################################################################################
option_host=
option_json_file=
option_sec_dir=wireguard
option_disk_image_size=25M
option_private_key_cmd=
option_tmp_file=
option_umount=0

################################################################################
function usage() {
  cat <<EOF
Usage: $(basename "$0") [options] name json-file

  -h      This message
  -p CMD  Command to run to get the WireGuard private key
  -s DIR  Use DIR as a secure directory for writing sensitive files
  -u      Unmount the directory created in another run

Generate WireGuard configuration files for the named device.  Also
generates QR codes.  All files are placed in an encrypted disk image
by default.  The disk image will be encrypted with a random password
so don't store important files in there.

NOTE: sudo will be used to get enough permissions to create the
encrypted directory.  You can also use the -s option with an existing
(secure) directory to avoid creating one.

Arguments:

  - name:

    The name of the peer to generate the configuration fore.

  - json-file:

    A JSON configuration file generated by the
    tilde.programs.wireguard module.  Generate this file from a NixOS
    configuration using the 'nix eval' command.  For example, for the
    host 'falken' use:

      nix eval --json \\
        .#nixosConfigurations.falken.config.tilde.programs.wireguard
EOF
}

################################################################################
function cleanup() {
  if [[ -n "$option_tmp_file" ]] && [[ -e "$option_tmp_file" ]]; then
    rm "$option_tmp_file"
  fi
}

################################################################################
function create_secure_directory() {
  if [[ ! -d "$option_sec_dir" ]]; then
    option_tmp_file=$(mktemp)
    openssl rand -hex 20 >"$option_tmp_file"
    trap cleanup EXIT

    make-encrypted-disk-image \
      -b "$option_disk_image_size" \
      -k "$option_tmp_file" \
      "${option_sec_dir}.img"

    mkdir -p "$option_sec_dir"

    mount-encrypted-dev \
      -k "$option_tmp_file" \
      "${option_sec_dir}.img" "$option_sec_dir"
  fi
}

################################################################################
function main() {
  local private_key

  while getopts "hp:s:u" o; do
    case "${o}" in
    h)
      usage
      exit
      ;;

    p)
      option_private_key_cmd=$OPTARG
      ;;

    s)
      option_sec_dir=$OPTARG
      ;;

    u)
      option_umount=1
      ;;

    *)
      exit 1
      ;;
    esac
  done

  shift $((OPTIND - 1))

  if [[ "$option_umount" -eq 1 ]]; then
    mount-encrypted-dev -u "$option_sec_dir"
    exit
  fi

  if [[ $# -ne 2 ]]; then
    echo >&2 "ERROR: missing name or json-file"
    exit 1
  fi

  option_host=$1
  option_json_file=$2

  if [[ -z "$option_private_key_cmd" ]]; then
    option_private_key_cmd="echo PRIVATE_KEY_NOT_GIVEN"
  fi

  bin=$(realpath "$(dirname "$0")")
  option_sec_dir=$(realpath "$option_sec_dir")
  option_json_file=$(realpath "$option_json_file")
  private_key=$("$SHELL" -c "$option_private_key_cmd")

  create_secure_directory

  (
    cd "$option_sec_dir" || exit 1

    "$bin/wg-gen.py" \
      --read-private-key \
      --host "$option_host" \
      --all "$option_json_file" \
      <<<"$private_key"

    find . \
      \( -type d -name 'lost+found' -prune \) -o \
      -type f \
      -name '*.cfg' \
      -exec qrencode -r '{}' -o '{}.png' ';'
  )
}

################################################################################
main "$@"
