#!/usr/bin/env bash

# Use a browser instance that is attached to a XMonad named scratch pad.

set -eu
set -o pipefail

name=sidebar

if [ $# -gt 0 ]; then
  # When opening a URL in the sidebar browser first ensure that
  # virtual monitor is displayed:
  hlwm-scratchpads.sh browser-sidebar
fi

# Now send all arguments to the browser-profile script:
browser-profile "$name" "$@"
