#!/usr/bin/env bash

################################################################################
#
# Call the configured browser.  Maybe one day this will map arguments
# so if I'm not using a chromium-based browser I can still use
# chromium-like arguments.
#
################################################################################
set -eu
set -o pipefail

################################################################################
if [ -n "${BROWSER:-}" ]; then
  "$BROWSER" "$@"
else
  # Focus an existing browser, or start a new one:
  if ! superkey-find-window.sh -cfa firefox; then
    if [ $# -eq 0 ]; then
      firefox --browser
    else
      firefox --new-window "$@"
    fi
  else
    if [ $# -gt 0 ]; then
      # If there are arguments then we should pass them on.  Otherwise
      # assume we were called simply to focus the browser window.
      firefox "$@"
    fi
  fi
fi
