#!/usr/bin/env bash

################################################################################
set -eu
set -o pipefail

################################################################################
usage() {
  echo "Usage: $(basename "$0") default-image directory background-color"
}

################################################################################
if [ $# -ne 3 ]; then
  ussage
  exit 1
fi

default_lock_image=$1
image_directory=$2
background_color=$3

################################################################################
# Actions to take before locking the screen.
preflight() {
  # Remove SSH keys from the agent:
  if [ "${SSH_AUTH_SOCK:=${XDG_RUNTIME_DIR:=/run/user/$(id -u)}/ssh-agent}" ]; then
    export SSH_AUTH_SOCK
    ssh-add -D || :
  fi

  # Kill gpg-agent so all passphrases are cleared:
  pkill gpg-agent || :

  # Set delay before turning monitor off:
  xset +dpms dpms 300 600 900

  # Also need to pause Dunst so notifications don't show up:
  pkill -SIGUSR1 dunst || :
}

################################################################################
restore() {
  # Disable monitor blanking:
  xset -dpms

  # Resume notifications:
  pkill -SIGUSR2 dunst || :
}
trap restore EXIT

################################################################################
preflight &

# Find an image to use:
file=$(random-file -i \
  -d "$image_directory" \
  -D "$default_lock_image")

# See if the file is in the cache:
cache=$(image-cache -i "$file")

if [ -e "$cache" ]; then
  image=$cache
else
  image=$default_lock_image
fi

# Lock it!
i3lock \
  --nofork \
  --tiling \
  --image="$image" \
  --color="$background_color" \
  --ignore-empty-password \
  --show-failed-attempts
