#!/usr/bin/env bash

################################################################################
set -eu
set -o pipefail

################################################################################
usage() {
  echo "Usage: $(basename "$0") default-image background-color"
}

################################################################################
if [ $# -ne 2 ]; then
  ussage
  exit 1
fi

default_lock_image=$1
background_color=$2

################################################################################
# Actions to take before locking the screen.
preflight() {
  # Set delay before turning monitor off:
  xset +dpms dpms 300 600 900

  # Stop the compositor since it breaks i3lock:
  systemctl --user stop picom.service || :

  # Also need to pause Dunst so notifications don't show up:
  pkill -SIGUSR1 dunst || :

  # Stop the music player:
  player-mpris-tail stop || :
}

################################################################################
restore() {
  xset dpms 0 0 0
  systemctl --user start picom.service || :
  pkill -SIGUSR2 dunst || :
}
trap restore EXIT

################################################################################
preflight &

# Find an image to use:
file=$(random-file -i \
  -d ~/documents/pictures/backgrounds/lock-screen \
  -D "$default_lock_image")

# See if the file is in the cache:
cache=$(image-cache -i "$file")

if [ -e "$cache" ]; then
  image=$cache
else
  image=$default_lock_image
fi

# Lock it!
i3lock \
  --nofork \
  --tiling \
  --image="$image" \
  --color="$background_color" \
  --ignore-empty-password \
  --show-failed-attempts
