#!/bin/sh

################################################################################
# Print the name of a random file.
#
# Useful for selecting a random image for a lock screen or wallpaper
# setting application.

################################################################################
set -e
set -u

################################################################################
option_dir=$(pwd)
option_glob="[!.]*"
option_default=

################################################################################
usage() {
  cat <<EOF
Usage: $(basename "$0") [options]

  -d DIR  Pick a file from DIR [default: pwd]
  -D FILE Default file if no files are in DIR
  -g GLOB Name glob passed to find(1)
  -h      This message

EOF
}

################################################################################
while getopts "D:d:g:h" o; do
  case "${o}" in
  d)
    option_dir=$OPTARG
    ;;

  D)
    option_default=$OPTARG
    ;;

  g)
    option_glob=$OPTARG
    ;;

  h)
    usage
    exit
    ;;

  *)
    exit 1
    ;;
  esac
done

shift $((OPTIND - 1))

################################################################################
if [ ! -d "$option_dir" ]; then
  if [ -n "$option_default" ]; then
    realpath "$option_default"
    exit
  else
    exit 1
  fi
fi

file=$(
  find -L \
    "$option_dir" \
    '(' -name '.*' -prune ')' -or '(' \
    '(' -type f -or -type l ')' -and \
    -name "$option_glob" -print ')' |
    shuf -n 1
)

if [ -n "$file" ]; then
  realpath "$file"
elif [ -n "$option_default" ]; then
  realpath "$option_default"
else
  exit 1
fi
