name: "Build and Test"

on:
  pull_request:
    types: [ "opened", "synchronize", "reopened", "closed" ]
  push:
    branches: [ "nixos-*" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: nixbuild/nix-quick-install-action@v34
      - uses: cachix/cachix-action@v17
        with:
          name: pjones
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: macOS Package Only
        if: runner.os == 'macOS'
        run: nix build --print-build-logs

      - name: Linux Full Check
        if: runner.os == 'Linux'
        run: nix flake check --print-build-logs --max-jobs 1
